; firmware/platformio.ini
[env:rlcd42]
platform = espressif32@^6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  lovyan03/LovyanGFX@^1.1.16
  bblanchon/ArduinoJson@^7.1.0

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<api.cpp>
build_flags = -std=gnu++17 -I src
lib_deps =
  bblanchon/ArduinoJson@^7.1.0
